"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/app.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
const inter = Inter({ subsets: ["latin"] });

import { ConfigProvider, theme } from "antd";
import { Provider } from "react-redux";
import store from "@/redux/store";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <Provider store={store}>
            <ConfigProvider
              theme={
                {
                  // algorithm: theme.darkAlgorithm,
                }
              }
            >
              {children}
            </ConfigProvider>
          </Provider>
        </AntdRegistry>
      </body>
    </html>
  );
}
